// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsirbmgpxvobsirvmick.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzaXJibWdweHZvYnNpcnZtaWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzNTA0ODEsImV4cCI6MjA4NDkyNjQ4MX0.Oi0138NOxCUl2-51-1EvwAiy905Cahbxhg3IEIK61rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});